import type { Metadata } from "next";
import { Award, Cpu, HeartHandshake, Mic2, Sprout, Users } from "lucide-react";
import { ArrowUpRight } from "lucide-react";
import { PageHero, PaperCard, SectionHeading } from "@/components/ui";
import { getDiaryEntries } from "@/lib/cms";
import { formatJapaneseDate } from "@/lib/format";

export const metadata: Metadata = { title: "活動と研究", description: "Urban Bee Clubの歩み、教授と学生による日々の養蜂、IoT・AIを使った分蜂予測研究を紹介します。" };

export default async function ResearchPage() {
  const entries = await getDiaryEntries();
  return <><PageHero eyebrow="About & research" title="好きだから、毎日見る。記録する。考える。" description="養蜂は生き物との長い対話です。教授と学生が続ける日々の世話に、情報工学の観測と解析を重ねています。"/><div className="page-shell py-20">
    <section><SectionHeading eyebrow="Our story" title="2023年、屋上から始まりました。"><p>「ミツバチってすごい」という好奇心を起点に、養蜂・教育・研究をつなぐサークルとして活動しています。</p></SectionHeading><ol className="relative mt-12 border-l-4 border-peach pl-8 sm:ml-8 sm:pl-12"><Timeline year="2023.07" title="Urban Bee Club 設立" text="電気通信大学の公認サークルとして活動を開始。キャンパスでの養蜂と観察の基盤を整えました。"/><Timeline year="2024" title="観測と地域交流が広がる" text="巣箱の内検・採蜜と並行し、IoTセンサーの試作や、ミツバチの生態を伝える活動を展開。"/><Timeline year="Award" title="ミツバチサミット 優秀賞" text="養蜂と情報技術を横断する取り組みが評価されました。成果を次の研究と教育へつなげています。"/><Timeline year="Now" title="羽音から分蜂の兆しを探る" text="温湿度・重量に加え、音の時系列データをAIで解析。早期の変化検出を目指しています。" last/></ol></section>
    <section className="mt-28 grid overflow-hidden rounded-[2.5rem] bg-bark text-cream lg:grid-cols-2"><div className="relative min-h-96 bg-[radial-gradient(circle_at_30%_30%,rgba(255,216,90,.35),transparent_30%),linear-gradient(145deg,#426B36,#243b20)] p-8 sm:p-12"><div className="absolute inset-0 opacity-15 [background-image:radial-gradient(#fff_1px,transparent_1px)] [background-size:18px_18px]"/><div className="relative flex h-full flex-col justify-between"><HeartHandshake className="h-14 w-14 text-pollen"/><blockquote className="mt-24 text-2xl font-black leading-relaxed">「数値だけでなく、<br/>今日の羽音や動きを見る。<br/>毎日の小さな違いが大切です。」</blockquote></div></div><div className="p-8 sm:p-12"><p className="font-black uppercase tracking-[.18em] text-pollen">The real story</p><h2 className="mt-4 text-3xl font-black">ハチを愛する教授の、日々の世話。</h2><div className="mt-6 space-y-5 leading-8 text-cream/75"><p>研究室の機器だけでは、ミツバチは守れません。暑さ、餌、女王蜂、ダニ、群れの勢い。天候や季節に合わせ、巣箱を開け、手と目で確かめます。</p><p>担当教授は、授業や研究の合間にも屋上へ足を運びます。その継続的な世話があるからこそ、学生は安全に学び、長期のデータを集められます。</p><p>テクノロジーは世話を置き換えるものではなく、気づきを増やす道具。これが私たちの研究の出発点です。</p></div></div></section>
    <section className="mt-28"><SectionHeading eyebrow="Technology with care" title="ミツバチに近づきすぎず、変化を知る。"/><div className="mt-10 grid gap-6 lg:grid-cols-3"><ResearchCard icon={<Cpu/>} label="IoT" title="巣箱センサーノード" text="温度・湿度・重量・振動を定期的に取得。省電力通信で、屋上から安全に時系列データを送ります。"/><ResearchCard icon={<Mic2/>} label="Sound AI" title="羽音の特徴量解析" text="周波数分布や時間変化を解析し、通常と異なる群れの状態を見つけるモデルを検討します。"/><ResearchCard icon={<Sprout/>} label="Prediction" title="分蜂の予兆検出" text="単一の値に頼らず、音・重量・温湿度・季節を組み合わせ、分蜂前の変化を早く捉えることを目指します。"/></div><div className="mt-6 rounded-2xl border border-bark/15 bg-peach/25 p-5 text-sm leading-7"><b>研究倫理とデータの読み方：</b>予測モデルは実験段階です。観測値は気象や機器状態にも影響されるため、内検結果と照合し、精度・誤検知・再現性を継続的に評価します。</div></section>
    <section className="mt-28"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><SectionHeading eyebrow="Bee diary" title="養蜂日誌・研究ノート"><p>Notionで公開された長文記録が、ここへ自動で届きます。</p></SectionHeading><span className="rounded-full bg-[#f4efd9] px-4 py-2 text-xs font-bold text-leaf">Notion と自動同期</span></div><div className="mt-10 grid gap-7 md:grid-cols-3">{entries.slice(0, 6).map((entry) => <PaperCard key={entry.id} className="article-card"><div className="article-card-visual" aria-hidden="true">✎</div><div className="article-card-data"><div className="flex items-center justify-between text-xs"><span className="rounded-full bg-peach/60 px-3 py-1 font-bold">{entry.category}</span><time dateTime={entry.publishedAt} className="text-bark/55">{formatJapaneseDate(entry.publishedAt)}</time></div><h3 className="mt-5 text-xl font-black">{entry.title}</h3><p className="mt-3 line-clamp-5 text-sm leading-7 text-bark/70">{entry.excerpt}</p>{entry.url && <a className="mt-5 inline-flex items-center gap-1 font-bold text-[#9D4712] hover:underline" href={entry.url} target="_blank" rel="noopener noreferrer">続きを読む <ArrowUpRight size={17}/></a>}</div></PaperCard>)}</div></section>
    <section className="mt-28"><SectionHeading eyebrow="What we do" title="研究室の外にも、ひらいていく。"/><div className="mt-10 grid gap-6 sm:grid-cols-3"><SimpleActivity icon={<Users/>} title="学内活動" text="定期内検、採蜜、データ観測、勉強会。初心者も安全講習から参加します。"/><SimpleActivity icon={<Award/>} title="発表・展示" text="研究成果や養蜂の学びを、学園祭やミツバチ関連イベントで共有します。"/><SimpleActivity icon={<Sprout/>} title="地域・教育" text="子供から大人まで楽しめる出前授業や観察企画の相談を受け付けます。"/></div></section>
  </div></>;
}

function Timeline({ year, title, text, last = false }: { year: string; title: string; text: string; last?: boolean }) { return <li className={last ? "relative" : "relative pb-12"}><span className="absolute -left-[43px] top-1 h-5 w-5 rounded-full border-4 border-cream bg-honey sm:-left-[59px]"/><p className="text-sm font-black tracking-widest text-leaf">{year}</p><h3 className="mt-2 text-2xl font-black">{title}</h3><p className="mt-3 max-w-3xl leading-8 text-bark/70">{text}</p></li>; }
function ResearchCard({ icon, label, title, text }: { icon: React.ReactNode; label: string; title: string; text: string }) { return <PaperCard><div className="flex items-center justify-between"><div className="text-honey [&>svg]:h-10 [&>svg]:w-10">{icon}</div><span className="font-black tracking-widest text-leaf/60">{label}</span></div><h3 className="mt-8 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-bark/70">{text}</p></PaperCard>; }
function SimpleActivity({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="border-t-4 border-honey pt-5"><div className="text-leaf [&>svg]:h-8 [&>svg]:w-8">{icon}</div><h3 className="mt-4 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-bark/70">{text}</p></div>; }
