import type { Metadata } from "next";
import { Activity, CloudSun, Database, Droplets, Scale, ThermometerSun } from "lucide-react";
import { SensorChart } from "@/components/sensor-chart";
import { PageHero, PaperCard, StatusPill } from "@/components/ui";
import { formatJapaneseDate } from "@/lib/format";
import { getDashboardData } from "@/lib/dashboard";

export const metadata: Metadata = { title: "スマート巣箱", description: "調布キャンパスの巣箱から、温度・湿度・重量・活動量をやさしく可視化します。" };

export default async function DashboardPage() {
  const data = await getDashboardData(); const latest = data.readings.at(-1);
  return <><PageHero eyebrow="Smart hive dashboard" title="巣箱の今を、そっと見る。" description="温度・湿度・重さ・出入りの変化をセンサーで記録。ふだんは見えない群れのリズムを、ミツバチを驚かせずに見守ります。"/><div className="page-shell py-16"><div className="flex flex-col gap-4 rounded-3xl border border-bark/10 bg-white p-5 shadow-paper sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-leaf">観測地点</p><h2 className="mt-1 text-xl font-black">{data.hiveName}</h2></div><div className="flex flex-wrap items-center gap-3"><StatusPill status={data.status}/><span className="text-xs text-bark/60">最終更新 {formatJapaneseDate(data.lastUpdated)} {new Date(data.lastUpdated).toLocaleTimeString("ja-JP", { hour: "2-digit", minute: "2-digit" })}</span></div></div>{data.status !== "live" && <div className="mt-5 flex items-start gap-3 rounded-2xl bg-peach/40 p-5" role="status"><CloudSun className="mt-1 shrink-0 text-[#9D4712]"/><p className="leading-7"><b>現在、ハチたちはお休み中（データ集計中）です。</b><br/><span className="text-sm text-bark/70">センサーから新しい便りが届くまで、{data.status === "demo" ? "サンプルデータ" : "最後に取得できたデータ"}を表示しています。</span></p></div>}<div className="mt-8 grid gap-6 md:grid-cols-2">{latest && <><PaperCard><SensorChart readings={data.readings.slice(-24)} metric="temperature"/></PaperCard><PaperCard><SensorChart readings={data.readings.slice(-24)} metric="humidity"/></PaperCard><PaperCard><SensorChart readings={data.readings.slice(-24)} metric="weight"/></PaperCard><PaperCard><SensorChart readings={data.readings.slice(-24)} metric="activity"/></PaperCard></>}</div><section className="mt-16" aria-labelledby="meaning"><h2 id="meaning" className="section-title">数字から、何がわかる？</h2><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={<ThermometerSun/>} title="温度" text="育児圏の保温や、群れの体温調節の変化を捉えます。"/><Metric icon={<Droplets/>} title="湿度" text="結露や蜜の熟成に関わる巣内環境を見守ります。"/><Metric icon={<Scale/>} title="重量" text="貯蜜、採餌、分蜂などによる巣箱全体の変化を読みます。"/><Metric icon={<Activity/>} title="活動量" text="巣門の出入りや振動から、日々のリズムを推定します。"/></div></section><section className="mt-16 rounded-[2rem] bg-bark p-7 text-cream sm:p-10"><div className="grid gap-8 md:grid-cols-[auto_1fr]"><Database className="h-12 w-12 text-pollen"/><div><h2 className="text-2xl font-black">データは「診断」ではなく、気づきの手がかり</h2><p className="mt-4 max-w-3xl leading-8 text-cream/75">センサー値だけで群れの健康を断定せず、天候、季節、内検での観察と組み合わせます。異常値は機器のずれや通信欠損も確認し、ミツバチへの不要な介入を避けます。</p></div></div></section></div></>;
}

function Metric({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <PaperCard><div className="text-honey [&>svg]:h-8 [&>svg]:w-8">{icon}</div><h3 className="mt-4 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-7 text-bark/70">{text}</p></PaperCard>; }
